product_homepage:
    path:     /home
    defaults: { _controller: ProductBundle:Default:index }
Ajouter_Categorie:
    path:     /AjouterCategorie
    defaults: { _controller: ProductBundle:Default:AjouterCategorie }
Ajouter_Marque:
    path:     /AjouterMarque
    defaults: { _controller: ProductBundle:Default:AjouterMarque }
Ajouter_Produit:
    path:     /AjouterProduit
    defaults: { _controller: ProductBundle:Default:AjouterProduit}
Afficher_Produits:
    path:     /AfficherProduits
    defaults: { _controller: ProductBundle:Default:AfficherProduits}
Ajouter_Promotion:
    path:     /AjouterPromotion
    defaults: { _controller: ProductBundle:Default:AjouterPromotion}
Modifier_Produit:
    path:     /ModifierProduit/{id}
    defaults: { _controller: ProductBundle:Default:UpdateProduit}
Afficher_Produit:
    path:     /AfficherProduit
    defaults: { _controller: ProductBundle:Default:AfficherProduit}
Delete_Produit:
    path:     /DeleteProduit/{id}
    defaults: { _controller: ProductBundle:Default:DeleteProduit}
ImageAccueil:
    path:     /ImageAccueil
    defaults: { _controller: ProductBundle:Default:SetImageAccueil}
panier:
    path:     /panier
    defaults: { _controller: ProductBundle:Default:Cart}
cart:
    path:     /cart
    defaults: { _controller: ProductBundle:Default:Cart}