<?php

namespace ProductBundle\Repository;

/**
 * ImageAccueilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageAccueilRepository extends \Doctrine\ORM\EntityRepository
{
}
